pusher/pusher-js

- src/pusher.js
Don't break in mysterious way when the user forgets to add the `new`
keyword like this:
var pusher = Pusher("key");
> Allow to forgo the `new` keyword

- src/pusher.js
This changes intends to simplify the recommended way for pusher-js
to enable logging.
The previously recommended way:
Pusher.log = function(message) {
if (window.console && window.console.log) {
window.console.log(message);
}
};
The new recommended way:
Pusher.verbose = true;
This change is backward-compatible. If someone installs his own logger
then `Pusher.verbose` is simply ignored.
In old IE `Pusher.verbose` is also ignored.
> Introduce simplified debug logging

- README.markdown
We need better documentation about passing CSRF tokens through the library for auth endpoints and should encourage people not to disable CSRF protection for such routes (especially for RoR)
@zimbatm
> Document CSRF tokens in README

- src/pusher.js
Warnings are too easily ignored, and this one will definitely become an
error once we try to connect, so there's no point continuing
> Throw when app_id is not specified

- spec/javascripts/helpers/mocks.js
- spec/javascripts/integration/core/pusher_spec.js
- spec/javascripts/unit/core/channels/channel_spec.js
- spec/javascripts/unit/core/pusher_spec.js
- src/core/channels/channel.ts
- src/core/pusher.ts
Following on from the discussion in #196, adds a method to reinstate a cancelled subscription. We should now be able to handle arbitrary chains of subscriptions and unsubscriptions – where the final method is always respected – regardless of the timings.
e.g. subscribe -> unsubscribe -> subscribe -> subscribe -> unsubscribe -> subscribe = subscribe
@hph
> Subscription unsubscription robustification

- CHANGELOG.markdown
- README.markdown
- spec/javascripts/unit/core/channels/channel_spec.js
- spec/javascripts/unit/core/channels/presence_channel_spec.js
- spec/javascripts/unit/core/channels/private_channel_spec.js
- spec/javascripts/unit/core/events_dispatcher_spec.js
- spec/javascripts/unit/core/pusher_spec.js
- src/core/events/dispatcher.ts
- src/core/pusher.ts
A customer pointed out that `unbind_all` didn't do what they expected. In particular it didn't reverse `bind_all`. Upon further inspection `unbind_all` was implemented identically to `unbind` and in fact all occurrences of `unbind_all()` can safely be replaced by `unbind()`. This also means that there is no way of removing global bindings (of the `bind_all` variety) short of directly mutating `channel.global_callbacks`.
After discussion in Slack we came to the conclusion that an `unbind_all` method should do just that, remove *all* bindings, and that `bind_all` should be replaced by `bind_global` and it's inverse `unbind_global` to avoid ambiguity.
This is a breaking change, but any use of `unbind_all()` will continue to work as expected (unless anyone was exploiting the fact that …
> Prod 1211 unbind all

- src/runtimes/worker/auth/fetch_auth.ts
By default the Fetch API doesn't send any cookies, even for same-origin
requests [1].  This presents a problem when using the fetch API against a
web framework that relies on cookies for authentication (like Django).
Note that the worker runtime is typically not used from the browser, except
when needed to work around issues with conflicts between multiple versions
of Pusher existing on the same page.  One example of when this happens is
if a third-party widget is bundling Pusher, and the main app is also trying
to use it.  For example: [2].
Without this patch, it's not possible to set up authenticated connections
against a Django app with CSRF protection enabled while using the worker
runtime.  With the patch, all's well.
[1] https://developer.mozilla.org/en-US/docs/Web/API/Request/creden …
> worker: fetch_auth: Send credentials

- src/runtimes/react-native/net_info.ts
Calling .done() crashed app on react-native@0.42.3 with .done undefined.
/cc @hph
> Change .done() to .then() in react-native

- README.markdown
- spec/javascripts/unit/core/channels/private_channel_spec.js
- src/core/auth/options.ts
- src/core/auth/pusher_authorizer.ts
- src/core/options.ts
- src/core/utils/factory.ts
This PR adds an option to use when configuring the Pusher client to override the behavior of the authorization.  My original use case was needing to pass a header along with my request that was only known at the time of the request and this solves that problem but also seems to solve a few other open issues.  Most importantly https://github.com/pusher/pusher-js/issues/165.
Open to suggestions for improvements.
/cc @hph
> Allow specifying a custom authorizer

- spec/javascripts/unit/core/channels/channel_spec.js
- src/core/channels/channel.ts
If Pusher disconnects (manually, or when network blips out and changes) while a channel subscription is happening (but is not yet successful), the channel is stuck in a pending subscription state. This means that when Pusher re-establishes connection and tries to re-subscribe channels, it skips over channels that are pending subscription. 
This results in the issue seen in #223 , and can be reproduced by going to http://test.pusher.com/, click disconnect button, then quickly click the connect and then disconnect again before the pusher channel subscription succeeds.
This fix resets `Channel.subscriptionPending` to `false` when a disconnect happens.
/cc @hph
> reset subscriptionPending if disconnect happens while subscribing

- dist/react-native/pusher.js
- src/runtimes/react-native/net_info.ts
Update React Native NetInfo usage ('change' event and 'fetch' module deprecated)
/cc @hph
> Update React Native NetInfo usage -- 'change' and 'fetch()' deprecated

- README.md
Use `const socket` everywhere
/cc @hph
> consistent naming of socket var

- src/core/channels/encrypted_channel.ts
- src/core/errors.ts
Attempts a single re-auth if decryption fails in case the key has been rotated. IMO the odds of a re-auth succeeding on the subsequent retries is low enough that it's not worth the added conceptual complexity at this point.
The other significant change is that rather than throwing errors, warnings are logged. This is what we are doing in other error cases when handling events:
https://github.com/pusher/pusher-js/blob/807b778463851f3a9b02114abf06f00f65e94d8f/src/core/pusher.ts#L151
So I thought it was better to keep it consistent. I'm not sure what even happens when throwing exceptions in "bind" callbacks. I actually think emitting error events which users can bind to would be the best approach, but not something I want to tackle now.
I also inlined the `handleEncryptedEvent` code. I think …
> Re-auth a single time if decryption fails

- spec/javascripts/unit/core/connection/connection_manager_spec.js
- src/core/connection/callbacks.ts
- src/core/connection/connection.ts
- src/core/connection/connection_manager.ts
- src/core/connection/handshake/handshake_payload.ts
At the moment, error codes/close actions are only respected when they're received during a handshake. Pusher server can close active connections with error codes that should be respected too (e.g. non-authorized connections are closed with a `4009` error)
This PR updates the connection manager to bind the error callbacks to the connection, aswell as the connection callbacks.
> Respect error codes when connected

- README.md
It updates the README regarding the cdn urls changing the version from `4.2` to `4.3`, the one that supports end-to-end Encryption right now.
> update README cdn version to 4.3

- .travis.build
- .travis.yml
- spec/config/karma/config.ci.js
- spec/config/karma/config.common.js
- spec/config/karma/integration.js
- spec/config/karma/unit.js
- spec/javascripts/unit/core/channels/channel_spec.js
- spec/javascripts/unit/web/transports/transports_spec.js
This functionality used to exist, and this PR re-adds it.
Unfortunately the tests for older browsers failed with:
```
22 03 2019 15:03:15.138:WARN [launcher.browserstack]: ie 8.0 (Windows 7) has not captured in 300000 ms, killing.
```
See: https://travis-ci.org/pusher/pusher-js/builds/509937975
So I have now configured tests using a new version of Chrome and Mac OS X.
I still think it's more valuable having this tested by CI than not.
We can re-introduce tests for other browsers as future work.
> Re-enable CI with Travis+BrowserStack

- README.md
- package-lock.json
- package.json
- src/d.ts/react-native/react-native.d.ts
- src/runtimes/react-native/net_info.ts
- webpack/config.react-native.js
NetInfo was removed from react-native core in version 0.60. The functionality was moved to an external package [@react-native-community/netinfo](https://github.com/react-native-community/react-native-netinfo). This PR updates pusher-js to use the new package.
The [@react-native-community/netinfo](https://github.com/react-native-community/react-native-netinfo) is added as a build dep, for type checking.
> Replace NetInfo w/ react-native-community version

- webpack/config.shared.js
tweetnacl works without Buffer when atob is available (which is the case
for web runtimes). So there is no reason to include the polyfill.
> Remove the useless Buffer polyfill from the build

- src/runtimes/react-native/net_info.ts
Uses the new API for @react-native-community/netinfo. We made the switch to @react-native-community/netinfo package in version 5.0.0 but we continued to use the old API.
This makes the minor changes required to use the new API, the functionality should be identical.
- [-] All new functionality has tests.
- [-] All tests are passing.
- [-] New or changed API methods have been documented.
> Use new netinfo api

- spec/javascripts/helpers/mocks.js
- spec/javascripts/helpers/pusher_integration.js
- spec/javascripts/helpers/pusher_integration_class.ts
- spec/javascripts/integration/index.web.js
- spec/javascripts/unit/core/connection/connection_spec.js
- spec/javascripts/unit/core/connection/handshake_spec.js
- spec/javascripts/unit/core/connection/protocol_spec.js
- spec/javascripts/unit/core/transports/transport_connection_spec.js
- src/core/connection/connection.ts
- src/core/connection/handshake/index.ts
- src/core/connection/protocol/protocol.ts
- src/core/index.js
- tsconfig.json
Duplicate of #370 to run the build in CI with browserstack credentials
This optimize the build to reduce the bundle size:
- it uses ES module as the output of Typescript (and so the input of webpack optimizations), as some of the most important optimizations performed by webpack are applied only on ES modules (see https://webpack.js.org/plugins/module-concatenation-plugin/)
- ~~it removes the useless Buffer polyfill injected by webpack due to tweetnacl using it (as it is using it only in node.js environments and has a different code path for the browser)~~ now extracted to #375
Here are the size of files for the web bundles (using `ls -shS1 dist/web/`, and keeping only the pusher files as sockjs and json2 are irrelevant for this PR):
before:
```
272K pusher.js
128K pusher.min.js
```
after …
> Optimize build

- README.md
Some old docs with `encrypted` made it into the readme
> Replace `encrypted` with `forceTLS` in README

- spec/javascripts/unit/core/channels/encrypted_channel_spec.js
- spec/javascripts/unit/core/logger_spec.js
- spec/javascripts/unit/core/pusher_authorizer_spec.js
- spec/javascripts/unit/core/pusher_spec.js
- spec/javascripts/unit/web/pusher_authorizer_spec.js
- spec/javascripts/unit/worker/pusher_authorizer_spec.js
- src/core/channels/channel.ts
- src/core/channels/encrypted_channel.ts
- src/core/channels/presence_channel.ts
- src/core/logger.ts
- src/core/pusher.ts
- src/runtimes/isomorphic/auth/xhr_auth.ts
- src/runtimes/web/auth/jsonp_auth.ts
- src/runtimes/worker/auth/fetch_auth.ts
There were three objectives of this PR:
1. If the auth response body is not JSON and logToConsole is set, it should log an error (not just mention no callback is bound)
2. All calls to Logger.warn logs should use console.warn if no default logger is set
3. Extend Logger to include an error method that calls console.error. Error logs should be updated to use this.
I made a couple of other changes while I was at it. The commit messages should be self-explanatory.
There are a couple of points I'd like feedback on in particular:
1. Connection errors are logged at warning level. This is because expected conditions like disconnects are included here. However it also includes error like failure to decode websocket messages, which I think should ideally be logged as errors.
2. @leesio it would be …
> Error logging improvements

- package-lock.json
- package.json
- spec/config/karma/config.ci.js
- spec/config/karma/config.common.js
- spec/config/karma/unit.js
- reduce the browser capture timeout from 3e5ms (300s) to 5e3ms (5s).
Previously if you didn't have a specific browser installed, the tests
would hang for a long time. Reducing this causes the tests to timeout
instead. I also updated the karma log level for the unit tests to surface this
error. This should fix issue #377 
- change browsers to test against
- use to ChromeHeadless
- remove Opera
- only use Safari if we have browserstack creds in the environment, this should prevent all non-pusher user's PRs from failing
- remove the coverage reporter, we're not making use of it really
> tweak some of the default test config params

- spec/javascripts/integration/core/cluster_config_spec.js
- spec/javascripts/integration/core/pusher_spec/index.js
- spec/javascripts/integration/core/timeout_configuration_spec.js
- spec/javascripts/unit/core/config_spec.js
- spec/javascripts/unit/core/connection/connection_manager_spec.js
- spec/javascripts/unit/core/defaults_spec.js
- spec/javascripts/unit/core/pusher_spec.js
- spec/javascripts/unit/core/transports/hosts_and_ports_spec.js
- spec/javascripts/unit/isomorphic/transports/hosts_and_ports_spec.js
- src/core/auth/options.ts
- src/core/auth/pusher_authorizer.ts
- src/core/config.ts
- src/core/connection/connection_manager.ts
- src/core/connection/connection_manager_options.ts
- src/core/defaults.ts
- src/core/options.ts
- src/core/pusher.ts
- src/core/strategies/strategy_builder.ts
- src/core/strategies/strategy_options.ts
- src/core/strategies/transport_strategy.ts
- src/core/transports/transport.ts
- src/core/utils/factory.ts
- src/runtimes/interface.ts
- src/runtimes/isomorphic/default_strategy.ts
- src/runtimes/web/default_strategy.ts
Separate Options from Config.
Previously the configuration of the library was very confusing. Configuration
objects were frequently composed by combining multiple different objects with
`Collections.extend`. Types annotations were absent and it made tracing the
config tricky.
There were also default configuration settings dotted all around the codebase
making it hard to see where parameters were set
This PR tries to improve that by separating the Options (an object of optional
parameters passed into the constructor by the user of the library) from the
Config (the full configuration object used by the library). The Config has
default parameters but can be overridden by Options
- create distinct types for the Config (used by the library) and the
Options (argument passed into the constructor …
> refactor config

- spec/javascripts/unit/core/pusher_with_encryption_spec.js
- src/core/pusher-with-encryption.ts
2 parameters can be set by the caller
```
import Pusher from 'pusher-js;
Pusher.logToConsole;
```
etc
We need to pass these properties on to the subclass
> pass global config to subclass

- README.md
Removes the beta label from the encrypted channels. I also updated the docs link as it was redirecting.
Do not merge this PR until private encrypted channels is actually released 🎉
> Remove beta label from encrypted channels

- package-lock.json
- package.json
In order for typescript to be able to properly resolve the module in consumer projects, tweetnacl needs to be a dependency of pusher-js
> Add tweetnacl as dependency

- react-native/index.js
Adds a `.` to the require for the `dist` folder from `react-native/index.js`
The `dist` folder is up a level in the `pusher-js` folder and I am currently getting the error:
```
Unable to resolve module `./dist/react-native/pusher` from `../node_modules/pusher-js/react-native/index.js`
```
> Update where react-native looks for dist

- README.md
Updating the docs regarding React Native implementation of encrypted channels.
Debatable, cause I saw changes in the previous commits, but the whole note still presents.
But do the note really still needed? It's plainly saying that encryption channels will not work. But they are actually working even without crypto library onboard.
> Deleted the note for not working RN builds

- src/runtimes/react-native/tweetnacl-dummy.ts
- src/runtimes/react-native/tweetnacl-util-dummy.ts
Deleted dummy files for old encryption channels implementation for React Native
As I see, it's not needed anymore?
Tested by building new react-native build and try it with encryption channels on our app
> deleted dummy tweetnacl libs for RN

- spec/javascripts/unit/core/channels/encrypted_channel_spec.js
- src/core/channels/encrypted_channel.ts
As per https://github.com/pusher/pusher-js/issues/437.
If the handler throws an error, we catch it and discard it. We shouldn't be doing anything with the caller's handlers.
> Don't catch and discard errors thrown by handlers

- spec/javascripts/unit/core/connection/connection_manager_spec.js
- spec/javascripts/unit/core/connection/connection_spec.js
- src/core/connection/connection.ts
- src/core/connection/connection_manager.ts
Hopefully fixes #464 
At the moment each layer (`TransportConnection`, `Connection` and `ConnectionManager`) wrap errors in a `WebSocketError` object, leading to nested errors as described in #464. This PR removes the wrapping from the `Connection` and `ConnectionManager`. All layers emitted to these layers should already be wrapped.
> don't wrap errors from transport

- spec/javascripts/unit/core/channels/channel_spec.js
- spec/javascripts/unit/core/pusher_spec.js
- src/core/channels/channel.ts
- src/core/pusher.ts
Resolves #255 
Currently if an auth request fails, a channel remains in a "subscriptionPending" state meaning it isn't possible to attempt to subscribe to the channel again. This PR clears the "subscriptionPending" state if the auth request fails, meaning it is possible to call `unsubscribe` and then `subscribe` again, to reattempt the subscription.
In order to do this, I made a slight change to the `unsubscribe` method too, so that the unsubscribe message is only sent over the websocket if the channel is actually subscribed. It appears that previously, while the websocket is connected, a channel could only be in the "subscriptionPending" or "subscribed" state. But now it's possible for channels to be in a state where they aren't subscribed and also aren't pending (if the auth request …
> Fix stuck subscription pending state

- package.json
This adds a react-native key to package.json. For some reason, Metro bundler needs this when pusher-js is a nested dependency (otherwise it tries to use the web runtime)
> Adds react-native key to package.json

- package-lock.json
- package.json
Fixes #494 - Upgrades the version of `faye-websocket` to 0.11.3.
N/A - only change is dependency version.
> Upgrade faye-websocket to 0.11.3

- package-lock.json
- package.json
Pusher's version of `@react-native-community/netinfo` is out-of-date, which leads to issues in React Native (and Expo), namely the following error (due to mismatched versions):
```
RNCNetInfo.getCurrentState got 2 arguments, expected 3
```
This should resolve the above issue.
> Update @react-native-community/netinfo to 5.9.7

- webpack/config.worker.js
This should allow the `pusher-js/worker` to be included in a bundle with the instructions already provided in the README
> Set worker webpack ouput libraryTarget to umd

- .gitmodules
-  Replaces the git protocol with HTTPS
More details here https://github.blog/2021-09-01-improving-git-protocol-security-github/
Git protocol is completely dropped as of 15 March 2022
* [FIXED] Replaced GIT protocol with HTTPS #587
> Replace git protocol with HTTPS in gitsubmodules file 

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/release_pr.yml
Update release_pr workflow to not pull from private repo cos that won't
work on external PRs.
The release_pr doesn't work on external PRs because it depends on an
action from a private repo (pusher/actions). External PRs can't use
GitHub Secrets to run Actions which is required in this case to copy an
action from a private repo.
Related to https://github.com/pusher/public_actions/pull/1
> Update release_pr workflow to not pull from private repo

- package-lock.json
- package.json
- spec/config/karma/config.common.js
- spec/javascripts/unit/core/connection/connection_manager_spec.js
- spec/javascripts/unit/core/http/http_request_spec.js
- spec/javascripts/unit/core/transports/transport_connection_spec.js
Small fixes and upgrades to fix failures in CI .
> Upgrade jasmine to 4.5.0

- package-lock.json
- spec/javascripts/helpers/mocks.js
- spec/javascripts/unit/core/connection/connection_manager_spec.js
- spec/javascripts/unit/core/pusher_spec.js
- src/core/connection/connection_manager.ts
- src/core/options.ts
- src/core/pusher.ts
- types/src/core/connection/connection_manager.d.ts
- types/src/core/options.d.ts
- types/src/core/pusher.d.ts
This PR introduces a way to tell Pusher client to switch the traffic from one cluster/app to the other.
This is super useful especially in case where Pusher is experiencing some outages allowing you to switch the traffic to a stable cluster without having to deal with resubscribing yourself all the channels and bind all the callbacks to the right events.
```ts
const pusher = new Pusher('mt1Key', { cluster: 'mt1' });
const channel = pusher.subscribe('private-channel');
channel.bind('event', console.log);
// Detect pusher outage
pusher.switchCluster({ appKey: "us3Key", cluster: "us3" });
// Here you should expect that all channels and bindings are still working as expected.
```
- [Added] Introduce a new `.switchCluster` method to switch the Pusher client to a different cluster and …
> Expose a way to switch from one cluster/app to the other

- spec/javascripts/unit/core/pusher_spec.js
- src/core/auth/options.ts
- src/core/config.ts
- src/core/pusher.ts
- types/src/core/auth/options.d.ts
Initial Pusher Options passed to the constructor were ignored when calling `pusher.switchCluster`.
- [FIXED] Persist Initial Pusher Options
- [FIXED] Authorization Custom Handler typing https://github.com/pusher/pusher-js/issues/715
> Persist initial Pusher options
