README.markdown

@zimbatm could you give it a quick check please?

Document the unsubscribe method.

---

spec/javascripts/unit/pusher_spec.js
src/pusher.js

Missing from #142 which was merged a little hastily

Update specs for new throw

---

README.markdown

Following support request for documentation on how to use bind_all

Better documentation of bind_all methods

---

package.json

I think this is a mistake in this commit 71a771cb85ba71f70f90ec302533b4db3ad66d9a.

Move ts-loader from dependencies to devDependencies

---

dist/react-native/pusher.js
src/core/logger.ts

The connection error being stringified by logger can be circular in
react native.

Connection failure when app gets inactive causes a crash on iOS

---

README.markdown

Just to be clear.
/cc @jpatel531

Make it clear that disableStats do not affect the user account stats

---

bower.json

Fix issue whereby bower install would ignore minified dist files.
- [N/A] All new functionality has tests.
- [N/A] All tests are passing.
- [N/A] New or changed API methods have been documented.
/cc @hph

Fix bower install missing minified files.

---

README.markdown

Fix a typo in Readme.
/cc @hph

Readme: Fix typo

---

README.markdown

Fix inconsistent naming of pusher/socket object in README

---

README.md

...and tidy up a few other inconsistencies
/cc @hph

Include cluster in each example of socket creation

---

spec/javascripts/unit/core/utils/url_store_spec.js
src/core/channels/presence_channel.ts
src/core/pusher.ts
src/core/utils/url_store.ts
src/runtimes/isomorphic/auth/xhr_auth.ts

Fixes some bits that was missed in 3f35b3e34d2ef437b8f5c3dd40b75a7b70eed687
- [-] New or changed API methods have been documented.
/cc @hph

Update key names everywhere

---

src/core/connection/connection_manager.ts

- [-] All new functionality has tests.
- [-] New or changed API methods have been documented.
/cc @hph

Handle undefined connection edge case

---

spec/javascripts/unit/core/pusher_spec.js

- [-] New or changed API methods have been documented.
/cc @hph

Fix failing test, add test for cluster check

---

dist/react-native/pusher.js
src/runtimes/react-native/net_info.ts

This PR was opened because #254 was mistakenly closed.

React Native update

---

spec/javascripts/unit/isomorphic/transports/transports_spec.js
spec/javascripts/unit/web/transports/transports_spec.js
src/core/config.ts
src/core/defaults.ts
src/core/transports/url_schemes.ts
src/runtimes/isomorphic/default_strategy.ts
src/runtimes/web/default_strategy.ts

Add support for wsPath config option (just like httpPath config option)

Add support for wsPath config option [updated for 3.1]

---

.github/PULL_REQUEST_TEMPLATE.md

Remove cc @hph from PRs

---

README.md

Update README to 4.4

---

src/core/channels/encrypted_channel.ts

fix grammar

---

.github/ISSUE_TEMPLATE.md

Fix issue template formatting

---

README.md

Clarify the product naming in the README

Clarify product name in README

---

spec/config/karma/config.ci.js

Headless full

---

Makefile
webpack/config.shared.js
webpack/config.web.js
webpack/config.worker.js

rather than using the development mode, just disable minimize for non
.min.js bundles

all build should use production builds

---

src/core/channels/channels.ts
src/d.ts/constants/index.d.ts
webpack/config.node.js
webpack/config.react-native.js
webpack/config.web.js
webpack/config.worker.js

Inject a RUNTIME variable with webpack

---

webpack/config.worker.js

add comma missing from worker webpack config

---

README.md

bump version in README

---

README.md

This does not define supported versions precisely, because I'm not sure we have agreed on this yet

Add supported platforms list

---

src/runtimes/isomorphic/auth/xhr_auth.ts

We log an error when the authorizer fails. The error was a bit confusing and missed some spaces

Fix the error message when authorization fails

---

.github/PULL_REQUEST_TEMPLATE.md
.prettierrc
.travis.yml
package-lock.json
package.json
src/core/base64.ts
src/core/config.ts
src/core/defaults.ts
src/core/logger.ts
src/core/options.ts
src/core/pusher.ts
src/core/reachability.ts
src/core/socket.ts
src/core/util.ts
src/runtimes/interface.ts
webpack/config.node.js
webpack/config.react-native.js
webpack/config.shared.js
webpack/config.web.js
webpack/config.worker.js
webpack/dev.server.js
webpack/hosting_config.js

use prettier to enforce consistent style

use prettier to enforce consistent style

---

README.md

Fix unclear documentation around wss connections.

---

README.md

Fix variable names in readme

---

spec/config/karma/config.common.js

I changed it to Opera in a previous commit and forgot to change it back

use ChromeHeadless for minimal tests

---

README.md
spec/javascripts/integration/core/cluster_config_spec.js
spec/javascripts/integration/core/falling_back_spec.js
spec/javascripts/integration/core/pusher_spec/test_builder.js
spec/javascripts/integration/core/transport_lists_spec.js
spec/javascripts/unit/core/pusher_spec.js
src/core/options.ts
src/core/pusher.ts

Make stats opt in

---

README.md

mention ts declarations in README

---

src/core/auth/auth_transports.ts
src/core/pusher.ts
src/core/timeline/timeline_transport.ts
src/runtimes/interface.ts
types/src/core/auth/auth_transports.d.ts
types/src/core/pusher.d.ts
types/src/core/timeline/timeline_transport.d.ts
types/src/runtimes/interface.d.ts

Fix ts declarations

---

README.md
spec/javascripts/unit/core/pusher_spec.js
spec/javascripts/unit/core/transports/hosts_and_ports_spec.js
spec/javascripts/unit/isomorphic/transports/hosts_and_ports_spec.js
spec/javascripts/unit/web/transports/hosts_and_ports_spec.js
src/core/config.ts
src/core/options.ts

Changes the default setting of `forceTLS` to `true`

Default tls

---

LICENCE
src/core/pusher-licence.js

bump dates on licences for @annzenkina

---

with-encryption/index.d.ts

Adds typescript declarations for the `with-encryption` package.

add types for with-encryption

---

README.md
index.d.ts
spec/config/karma/config.ci.js
spec/javascripts/unit/core/channels/channel_spec.js
spec/javascripts/unit/core/channels/encrypted_channel_spec.js
spec/javascripts/unit/core/pusher_authorizer_spec.js
src/core/auth/options.ts
src/core/auth/pusher_authorizer.ts
src/core/channels/channel.ts
src/core/channels/encrypted_channel.ts
src/core/errors.ts
src/runtimes/isomorphic/auth/xhr_auth.ts
src/runtimes/web/auth/jsonp_auth.ts
src/runtimes/worker/auth/fetch_auth.ts

Updates the types/callback signature of authorizers to provide a more idiomatic experience.
Fixes #427

Update auth errors

---

react-native/index.d.ts
with-encryption/index.d.ts

Remove AuthInfo type for other builds

---

README.md

Adds a note about client events to the readme. Mentioned in #305

add a note to the README about client events

---

.github/workflows/release.yml
.github/workflows/release_pr.yml

Add a workflow to automate release process.
The workflow triggers on push event on the `master` branch. If and only when
we don't have a tag for the current version, it creates the tag and GitHub release
and then it publishes to the NPM and uploads the build to S3.

Create release workflow

---

.github/workflows/release_pr.yml
Makefile

Update release_pr to bump version & build.
Fix Makefile - We have a directory named worker which prevents make
command to run correctly.

Fix release_pr workflow

---

CHANGELOG.md
package-lock.json
package.json

Update CHANGELOG and package version for the 7.1.0-beta release

---

README.md

Updates the README to bring it in line with the users feature and the content at https://pusher.com/docs/channels/using_channels/connection/#channelauthorization-1231697137

Update README to remove legacy auth and replace it with userAuthentication and channelAuthorization

---

README.md

We missed some spots when updating the readme for the user changes. This PR addresses that.

Update readme on authorization

---

worker/with-encryption/index.js

Fix path in worker/with-encryption/index.js

---

README.md

* Remove React Native stuff from README

Update README with new React Native guidelines 

---

CHANGELOG.md

Fix changelog of v7.4.0

---

.github/workflows/run-tests.yml
Makefile
integration_tests_server/index.js
integration_tests_server/package-lock.json
integration_tests_server/package.json
spec/javascripts/helpers/node/integration.js
spec/javascripts/helpers/web/integration.js
spec/javascripts/integration/core/cluster_config_spec.js
spec/javascripts/integration/core/pusher_spec/test_builder.js
spec/javascripts/integration/web/dom/jsonp_spec.js

Set up a local server on the CI for the integration tests.

Update integration tests to use local server

---

spec/javascripts/unit/core/utils/url_store_spec.js

Reverts commit d1024af which was pushed in error.

Revert broken attempt to fix typo

---

README.md

Change doc accordingly to the real behavior

Fix error handling event parameter
